
shop1 = input("หยิบสินค้าครั้งที่ 1 :")
shop2 = input("หยิบสินค้าครั้งที่ 2 :")
shop3 = input("หยิบสินค้าครั้งที่ 3 :")
shop4 = input("หยิบสินค้าครั้งที่ 4 :")
shop5 = input("หยิบสินค้าครั้งที่ 5 :")
basket = []
basket.append(shop1)
basket.append(shop2)
basket.append(shop3)
basket.append(shop4)
basket.append(shop5)
print('1.',basket[0])
print('2.',basket[1])
print('3.',basket[2])
print('4.',basket[3])
print('5.',basket[4])